# This is a basic workflow to help you get started with Actions

name: Compile on upload

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    paths:
      - '**.tar.gz'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Display directory tree
      - name: Display directory tree
        run: tree -d

      # Extract the last uploaded source file
      - name: Extract the last uploaded source file 
        run: |
          cd Iphreeqc_source/
          tar -xf "$(\ls -\dt **.gz | head -n 1)"

      # Try enter extracted directory
      - name: Enter newly created directory (BUILD_FOLDER)
        run: |
          BUILD_FOLDER=$"$(\ls -1dt ./*/ | head -n 1)"
          cd ${BUILD_FOLDER}
          ls

      # Working directory
      - name: Working directory
        run: pwd 

      # Configure
      - name: Configure
        run: ./configure --prefix=Iphreeqc_compiled/${BUILD_FOLDER}      
        


