name: Compile on upload

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    paths:
      - '**.tar.gz'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    # Grant write permissions to the job for pushing
    permissions:
      contents: write
      pull-requests: write
      
    # Use the latest recommended Ubuntu runner
    runs-on: ubuntu-22.04
    timeout-minutes: 20

    steps:
      # Use the latest checkout action
      - uses: actions/checkout@v4

      # Display directory tree
      - name: Display directory tree
        run: tree -d

      # Extract the last uploaded source file
      - name: Extract the last uploaded source file 
        run: |
          cd Iphreeqc_source/
          BUILD_COMPRESSED=$(\ls -\dt **.gz | head -n 1)
          mkdir new
          tar -xf ${BUILD_COMPRESSED} --directory ./new
          cd new
          BUILD_FOLDER=$(basename $(ls -td ./*/ | head -1))
          cd *
          pwd
          ls
          mkdir compiled
          ./configure --prefix=/home/runner/work/phreeqc_web/phreeqc_web/Iphreeqc_source/new/${BUILD_FOLDER}/compiled
          make check
          make install 
          cd compiled/lib
          BUILD_FILE=$(ls -1 | head -n 1)
          cp ${BUILD_FILE} /home/runner/work/phreeqc_web/phreeqc_web/Iphreeqc_compiled/${BUILD_FILE}
#          cd /home/runner/work/phreeqc_web/phreeqc_web/Iphreeqc_compiled
#          git config --global user.name 'rispr'
#          git config --global user.email 'rispr@users.noreply.github.com'
#          git add /home/runner/work/phreeqc_web/phreeqc_web/Iphreeqc_compiled
#          git commit -am "compiled ${BUILD_FILE}"
#          git push            
          
      # This action replaces all your git commands
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          # The user that creates the commit
          commit-message: "feat: Add compiled library"
          # The title of the pull request
          title: "Automated compilation of new library"
          # A description for the pull request
          body: |
            This PR was automatically generated by a GitHub Action.
            It contains the newly compiled library file from the latest source upload.
          # The branch to create for this PR
          branch: "auto-compile-branch"          
          
          
          
          
