# This is a basic workflow to help you get started with Actions

name: Compile on upload

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    paths:
      - '**.tar.gz'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Display directory tree
      - name: Display directory tree
        run: tree -d

      # Extract the last uploaded source file
      - name: Extract the last uploaded source file 
        run: |
          cd Iphreeqc_source/
          BUILD_COMPRESSED=$(\ls -\dt **.gz | head -n 1)
          mkdir new
          tar -xf ${BUILD_COMPRESSED} --directory ./new
          cd new
          BUILD_FOLDER=$(basename $(ls -td ./*/ | head -1))
          cd *
          pwd
          ls
          mkdir compiled
          ./configure --prefix=/home/runner/work/phreeqc_web/phreeqc_web/Iphreeqc_source/new/${BUILD_FOLDER}/compiled
          make check
          make install 
          cd compiled/lib
          BUILD_FILE=$(ls -1 | head -n 1)
          cp ${BUILD_FILE} /home/runner/work/phreeqc_web/phreeqc_web/Iphreeqc_compiled/${BUILD_FILE}
          cd /home/runner/work/phreeqc_web/phreeqc_web/Iphreeqc_compiled
          git config --global user.name 'rispr'
          git config --global user.email 'rispr@users.noreply.github.com'
          git add /home/runner/work/phreeqc_web/phreeqc_web/Iphreeqc_compiled
          git commit -am "compiled ${BUILD_FILE}"
          git push            
          
          
          
          
          
